# Generated by Django 2.2.19 on 2023-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='task/', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Task3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='task/', verbose_name='Картинка')),
            ],
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Task1',
        ),
    ]
