# Generated by Django 2.2.19 on 2023-04-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_comment2_comment3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('answer', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='task/', verbose_name='Картинка')),
            ],
            options={
                'default_related_name': 'task',
            },
        ),
        migrations.RemoveField(
            model_name='comment2',
            name='task',
        ),
        migrations.RemoveField(
            model_name='comment3',
            name='task',
        ),
        migrations.DeleteModel(
            name='Comment1',
        ),
        migrations.DeleteModel(
            name='Comment2',
        ),
        migrations.DeleteModel(
            name='Comment3',
        ),
        migrations.DeleteModel(
            name='Task1',
        ),
        migrations.DeleteModel(
            name='Task2',
        ),
        migrations.DeleteModel(
            name='Task3',
        ),
    ]
